### ISSUE TITLE
After updating version - all favorites disappear

### ISSUE THREAD

**Issue by yonifra** [cnordvik/FotMobIssueTracker#11]
Updated today to latest beta version - All favorite teams and leagues have been removed from my favorites list.

**Comment by cnordvik** [comment]
That seems very strange. You are 100% sure you didn't do a reinstall? :-) We did not change anything related to that in the latest update...

**Comment by yonifra** [comment]
Yes, I did an update from the previous version to the latest Beta. I didn't uninstall and re-install the game (although, even if I had, I would expect the favorites to remain untouched)

**Comment by cnordvik** [comment]
We updated our play version and no users reported this so hope it is not an issue anymore!
