### ISSUE TITLE
Finished games sometimes display wrong score

### ISSUE THREAD

**Issue by yonifra** [cnordvik/FotMobIssueTracker#12]
Doesn't happen all the times, only with some games (See attachment)
The score is 0-0 but there were goals scored (which show in the game events list)
![2013-06-24 08 06 55](https://f.cloud.github.com/assets/726718/693483/7dad6e28-dc8c-11e2-94af-76f185dd3550.png)

**Comment by cnordvik** [comment]
Hmm. Can you let me know if it happens again? A restart of our server solved it this time, we will investigate some more.

**Comment by yonifra** [comment]
Sure, I'll keep an eye for this issue

**Comment by cnordvik** [comment]
Unable to reproduce this...
