### ISSUE TITLE
Cannot see the "Betting" tab

### ISSUE THREAD

**Issue by yonifra** [cnordvik/FotMobIssueTracker#13]
In games that haven't started yet, I cannot see the "Betting" tab so that I can see the odds and make bets

**Comment by cnordvik** [comment]
Restricted countries that won't see betting:

Australia 
Chinese Taipei
France
French Guyana
Guadeloupe
Hong Kong
Iran
Israel
Italy 
Netherlands
Martinique
Syria
Turkey
United States of America
