### ISSUE TITLE
Betting tab is enabled for restricted countries

### ISSUE THREAD

**Issue by yonifra** [cnordvik/FotMobIssueTracker#14]
The "Betting" tab is enabled even though I live in a betting restricted country (Israel)
See attachment
![screenshot_2013-06-27-10-29-23](https://f.cloud.github.com/assets/726718/714371/63304d82-defc-11e2-86df-490a4e650747.png)

**Comment by cnordvik** [comment]
I wanted you all to test it, sorry for not informing you :-)

**Comment by yonifra** [comment]
I see, no problem :+1:
