### ISSUE TITLE
Aggregate score is not correct

### ISSUE THREAD

**Issue by yonifra** [cnordvik/FotMobIssueTracker#16]
Olimpia won 2-0 in the first game, in the second game, however, Olimpia lost 0-1 and the aggregate is still 2-0
![screenshot_2013-07-11-10-53-19](https://f.cloud.github.com/assets/726718/780292/6914510e-e9ff-11e2-8642-6f77d2c05752.png)

**Comment by cnordvik** [comment]
Fixed!
