### ISSUE TITLE
"Access denied" error when trying to see the "News" section for some teams

### ISSUE THREAD

**Issue by yonifra** [cnordvik/FotMobIssueTracker#5]
When going to the "News" section for Argentina (for example), there's an access denied error being received from XML
![2013-06-15 12 11 36](https://f.cloud.github.com/assets/726718/657995/332cdc56-d5a9-11e2-9943-82d3ff94e2d7.png)

**Comment by yonifra** [comment]
Happens with all teams, not just Argentina

**Comment by cnordvik** [comment]
It is due to our backup server, not really a problem since it will be ok when we launch but I will leave the issue open for now
