### ISSUE TITLE
Full screen ad blocks access to FotMob

### ISSUE THREAD

**Issue by yonifra** [cnordvik/FotMobIssueTracker#6]
Every once in a while a fullscreen ad blocks the app, causing me to kill it and relaunch it.
![2013-06-14 23 20 36](https://f.cloud.github.com/assets/726718/657996/b39cbfc8-d5a9-11e2-9865-b8ad7fcf5fb4.png)

**Comment by cnordvik** [comment]
Did you click the ad, or did it appear like this without you clicking it?

**Comment by yonifra** [comment]
I don't usually click on ads, but I don't remember if I clicked on this on by mistake or not. It didn't re-occur since then

**Comment by cnordvik** [comment]
Could you not access the left menu and navigate away from this screen? Just wondering how serious this bug is as we have a new ad-provider in this release and won't launch with them if this is causing a problem...

**Comment by yonifra** [comment]
As I recall, the screen was "locked", the only thing I could access was the notifications bar.
I haven't encountered this again since, and I'll keep an eye on it if this happens again

**Comment by khchen428** [comment]
Hi @yonifra ,  this is Joe from MoPub (the new ad-provider).  I've been trying to nail down the issue you're seeing but haven't been successful - the same ad in your screenshot rendered correctly in my test build.
Do you mind letting us know the following:
1. the device your testing on
2. your Android OS version
3. where are you testing from?

Thanks,
Joe

**Comment by yonifra** [comment]
Hi Joe,

Here is the info you requested:
1. Samsung Galaxy SIII
2. Android 4.1.2 (Since then, I've upgraded to 4.2.2)
3. I'm testing from Israel, Tel Aviv area

Hope that helps,
Jonathan.

**Comment by cnordvik** [comment]
We moved away from MoPub, so closing this issue.
