### ISSUE TITLE
"Squad" section is always empty

### ISSUE THREAD

**Issue by yonifra** [cnordvik/FotMobIssueTracker#7]
See attached image:
![2013-06-15 13 55 07](https://f.cloud.github.com/assets/726718/658001/2fb66a64-d5aa-11e2-92c8-3286fed0ae2b.png)

**Comment by cnordvik** [comment]
Always? All teams? I just checked and Barcelona worked for me :-/

**Comment by yonifra** [comment]
Now it appears to be working for me too... (For Barcelona and all other teams)

**Comment by cnordvik** [comment]
Strange, let me know if it happens again...
