### ISSUE TITLE
Sound not audiable

### ISSUE THREAD

**Issue by yonifra** [cnordvik/FotMobIssueTracker#9]
Cannot hear sounds from FotMob, either Start / Finish sounds nor Goals.
Also, the sounds name isn't "default" like it used to be, but is 1246 or 1247 (probably the "default" text id)
Happened in latest version (from June 17th)

**Comment by cnordvik** [comment]
This is an issue we have seen sometimes but never understood why. We copy the sounds into the media library at startup if we cannot find them already. Seems like this has failed for some reason (maybe it couldn't access the SD card) and therefore but have lost the sounds. Can you set the sound again? And do you find the FotMob default sound if you try to change the sound for the goal?

**Comment by yonifra** [comment]
It happened to me in the prior versions as well, only there the string "default" was visible and now it's not.
I can see the notification sounds in my list of sounds, ("FotMob-Ding" and "Referee Whistle 02") and after setting them as the sounds and pressing the "Test notification" button I can hear the ding sound.
I'll test that today or tomorrow with a real life game.
UPDATE: Works with real life games (but only after reconfiguring the sounds myself in the settings)

**Comment by cnordvik** [comment]
Should work now :-)

**Comment by LarsEckart** [comment]
I think i have a similar problem.
I remember I had the sounds, but now all i hear are my default phone's sounds and i cant even select FotMob-Ding or Referee Whistle as sounds.

**Comment by cnordvik** [comment]
Hmm. In the next update we changed some sounds and fixed an issue so hopefully this bug is gone then.

**Comment by germanpeart** [comment]
I just downloaded the newest version. Still with the same problem :(

**Comment by cnordvik** [comment]
@germanpeart Can you try this one? https://dl.dropboxusercontent.com/u/25670071/FotMob14_4_widget_and_timezone.apk

We have changed to not play the sounds from the SD card unless you change the sound. So a clean install should always work 100% now.

**Comment by germanpeart** [comment]
Ok. Thank you so much. 
I hope it works. 
I really like this app
